In [20]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

file_path = Path.cwd().parent / "summary.csv"

df = pd.read_csv(file_path)

In [21]:
df.describe()

,Unnamed: 0,config.acc_threshold,config.epochs,config.eta,config.mini_batch_size,config.samples_per_worker,config.thread_count,config.thread_state,mean_peak_accuracy,mean_final_accuracy,mean_total_time,mean_training_time,mean_testing_time,run_count,seed_count
count,378.000000,378.0,378.0,378.000000,378.000000,378.0,378.0,378.0,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000
mean,188.500000,94.0,30.0,2.468889,119.534392,32.0,16.0,0.0,67.595916,67.518138,51.513816,47.671411,3.842405,2.925926,2.925926
std,109.263443,0.0,0.0,3.030551,85.914739,0.0,0.0,0.0,37.158472,37.142952,50.103086,46.436738,3.687172,0.341342,0.341342
min,0.000000,94.0,30.0,0.030000,32.000000,32.0,16.0,0.0,9.800000,9.800000,7.950933,7.326024,0.482651,1.000000,1.000000
25%,94.250000,94.0,30.0,0.100000,32.000000,32.0,16.0,0.0,16.661666,16.634166,8.766400,8.114988,0.656844,3.000000,3.000000
50%,188.500000,94.0,30.0,0.750000,64.000000,32.0,16.0,0.0,91.573331,91.548331,26.249969,24.259738,2.022254,3.000000,3.000000
75%,282.750000,94.0,30.0,3.000000,128.000000,32.0,16.0,0.0,95.876666,95.704163,115.607909,106.725334,8.697932,3.000000,3.000000
max,377.000000,94.0,30.0,9.000000,256.000000,32.0,16.0,0.0,98.436666,98.343330,138.644048,128.801651,9.842395,3.000000,3.000000

In [23]:
df.sort_values(by=["mean_final_accuracy"]).head(10)

,Unnamed: 0,config.acc_threshold,config.activation,config.epochs,config.eta,config.initializer,config.mini_batch_size,config.samples_per_worker,config.thread_count,config.thread_state,config.topology,mean_peak_accuracy,mean_final_accuracy,mean_total_time,mean_training_time,mean_testing_time,run_count,seed_count
377,377,94.0,relu,30,0.75,xavier_normal,32,32,16,0,"(784, 512, 128, 30, 10)",9.8,9.8,127.810730,119.142723,8.668012,2,2
376,376,94.0,relu,30,0.75,xavier_normal,32,32,16,0,"(784, 128, 30, 10)",9.8,9.8,26.439621,24.416637,2.022983,3,3
375,375,94.0,relu,30,1.00,xavier_normal,64,32,16,0,"(784, 128, 30, 10)",9.8,9.8,26.111314,24.245064,1.866251,3,3
374,374,94.0,relu,30,1.00,xavier_normal,64,32,16,0,"(784, 512, 128, 30, 10)",9.8,9.8,124.494113,115.367798,9.126315,3,3
373,373,94.0,relu,30,1.00,xavier_normal,128,32,16,0,"(784, 128, 30, 10)",9.8,9.8,25.406330,23.667943,1.738387,3,3
341,341,94.0,relu,30,3.00,xavier_normal,128,32,16,0,"(784, 512, 128, 30, 10)",9.8,9.8,111.742615,102.579224,9.163388,2,2
342,342,94.0,relu,30,3.00,xavier_normal,256,32,16,0,"(784, 30, 10)",9.8,9.8,8.709266,8.061519,0.647747,3,3
343,343,94.0,relu,30,3.00,xavier_normal,256,32,16,0,"(784, 128, 30, 10)",9.8,9.8,25.089887,22.887544,2.202343,3,3
344,344,94.0,relu,30,3.00,xavier_normal,256,32,16,0,"(784, 512, 128, 30, 10)",9.8,9.8,115.487080,106.108974,9.378104,2,2
345,345,94.0,relu,30,6.00,lecun_normal,32,32,16,0,"(784, 30, 10)",9.8,9.8,8.544777,7.899342,0.645435,3,3